#pragma once

#include <QApplication>
#include <QDialog>
#include <QFont>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QMainWindow>
#include <QPushButton>
#include <QSize>
#include <QString>
#include <algorithm>
#include <array>
#include <cppitertools/range.hpp>
#include <iostream>
#include <memory>
#include <typeinfo>
#include <utility>
